### ISSUE TITLE
Forced version update in F-Droid

### ISSUE THREAD

**Issue by Korb** [vbresan/HealthyBatteryCharging#13]
Currently in F-Droid and in IzzyOnDroid F-Droid Repo the latest version available for installation is 2.0.2. Although, 2.0.3 came out 4 days ago. Not to mention today's 2.0.4. Is it possible to force (accelerate) submit new releases for placement in F-Droid?

**Comment by vbresan** [comment]
According to their [FAQ](https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client), it can take up to 7 days for F-Droid to detect and publish an update. However, sometimes things seem to get [stuck](https://forum.f-droid.org/t/question-about-new-app-updates/22702). I'm not sure how it goes with IzzyOnDroid.

I have no idea how to accelerate updates; perhaps the best approach would be to ask on their forums.

In any case, if you would like to receive a notification as soon as a new release is available, you can subscribe to the [releases RSS channel](https://github.com/vbresan/HealthyBatteryCharging/releases.atom) and download and install the APK directly. Otherwise, *there is an app for that* (open source too) named [Obtainium](https://github.com/ImranR98/Obtainium).

**Comment by IzzySoft** [comment]
@Korb new releases should arrive at IzzyOnDroid within 24h of their becoming available here. If they don't, there's some issue. Luckily I just stumbled upon this issue here when looking to file another one, as I was not aware of the problem. It's fixed now (was a wrong parameter for the updater on the IoD end), so starting with the next sync around 6 pm UTC, HealthyBatteryCharging should be updated in timely manner again (to make sure it works properly now, I just manually triggered a scan and it immediately pulled the last version to staging).
